name: Deploy Laboratory
on:
  workflow_dispatch:
    inputs:
      version_semantica:
        description: 'Digite el tag que quiere generar para la imagen'
        required: true
        type: string  
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2
      - name: Checkout external
        uses: actions/checkout@v3
        with:
          repository: cabunga/external
          path: ./.github/workflows
          ref: 'main'        
      - name: Run Manual Steps
        run: |
          ls -altr /home/runner/work/workflow/workflow/.github/workflows
          ls -a .github/workflows
          echo "Running manual steps with input: ${{ github.event.inputs.version_semantica }}"
  Deploy_lab:
     uses: cabunga/external/.github/workflows/node.yml
     secrets: inherit
     with:
       build-command:  ${{ github.event.inputs.version_semantica }}
  
  
