name: Deploy 
on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Seleccione tag de repositorio de código'
        required: true
        type: choice
        options: [master ]
      Branch_Helm:
        description: 'Seleccione Branch de repositorio de Helm'
        required: true
        type: choice
        options: [ release]
      environment:
        description: 'Seleccione environment a desplegar'
        required: true
        type: choice
        options: 
          - 'UAT'
          - 'PRD'          
      

env:
  PARTITION_OTT: dom
  PARTITION_IPTV: cdominic
  PARENT_PARTITION: DOM
  SERVICE: mfw

jobs:
  Outputs:
    name: servicio a desplegar
    runs-on: ubuntu-latest
    environment: develop
    outputs:
      PARTITION_OTT: ${{ steps.outputs.outputs.PARTITION_OTT }}
      PARTITION_IPTV: ${{ steps.outputs.outputs.PARTITION_IPTV }}
      PARENT_PARTITION: ${{ steps.outputs.outputs.PARENT_PARTITION }}
      SERVICE: ${{ steps.outputs.outputs.SERVICE }}
    steps:
      - name: se desplegará servicio ${{ env.SERVICE }} en ${{ env.PARENT_PARTITION }}
        id: outputs
        run: |
            if [ "${{ inputs.Silo }}" == "Todos (ott/iptv)" ]; then
            
            echo "se desplegará en ${{ inputs.environment }} el servicio ${{ env.SERVICE }} para la partición ${{ env.PARTITION_OTT }} en ott"
            echo "se desplegará en ${{ inputs.environment }} el servicio ${{ env.SERVICE }} para la partición ${{ env.PARTITION_IPTV }} en iptv"
            fi

            if [ "${{ inputs.Silo }}" == "ott" ]; then
              echo "se desplegará en ${{ inputs.environment }} el servicio ${{ env.SERVICE }} para la partición ${{ env.PARTITION_OTT }} en ott"
            fi
            
            if [ "${{ inputs.Silo }}" == "iptv" ]; then
              echo "se desplegará en ${{ inputs.environment }} el servicio ${{ env.SERVICE }} para la partición ${{ env.PARTITION_IPTV }} en iptv"
            fi

            # se exportan outputs para usar variables en siguientes jobs del workflow principal
            echo "PARTITION_OTT=${{ env.PARTITION_OTT }}" >> "$GITHUB_OUTPUT"
            echo "PARTITION_IPTV=${{ env.PARTITION_IPTV }}" >> "$GITHUB_OUTPUT"
            echo "PARENT_PARTITION=${{ env.PARENT_PARTITION }}" >> "$GITHUB_OUTPUT"
            echo "SERVICE=${{ env.SERVICE }}" >> "$GITHUB_OUTPUT"
            echo "secret ${{secrets.USER}}"

