name: Deploy Laboratory
on:
  workflow_dispatch:
    inputs:
      version_semantica:
        description: 'Digite el tag que quiere generar para la imagen'
        required: true
        type: string  
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2
      - name: Checkout davivienda-colombia/davi-coe-action-files-changed-analyze-pipeline
        uses: actions/checkout@v3
        with:
          repository: cabunga/external
          ref: 'main'        
      - name: Run Manual Steps
        run: |
          ls
          echo "Running manual steps with input: ${{ github.event.inputs.version_semantica }}"
  deploy:    
    name: Deploy lab
    uses: cabunga/external/.github/workflows/node.yml
    with:
       build-command:  ${{ github.event.inputs.version_semantica }}
  
